### ISSUE TITLE
Python version check logic has a minor issue

### ISSUE THREAD

**Issue by kongqp** [kee1ongz/MiniCAT#1]
Hello,

I found a small issue in the Python version check logic within the initialize.sh file. In line 12, the expression ${PYTHON_VERSION:7:1} -ge 6 should use 9 instead of 7 to correctly capture the minor version of Python.

Specifically:
```
${PYTHON_VERSION:7:1} -ge 6
```
should be:
```
${PYTHON_VERSION:9:1} -ge 6
```
This adjustment will ensure that the script correctly checks the Python minor version when determining compatibility.

Thank you for looking into this!

**Comment by kee1ongz** [comment]
Hi kongqp,

Thanks for the catch! Issue confirmed and fixed. 🙏

**Comment by kee1ongz** [comment]
Fixed Python version check.
